{
 "title": "CASPER VALIDATOR ALPHA BOARD",
 "description": "Work in progress",
 "time": { "from": "2021-04-07T07:52:56.000Z", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "casper_exporter_is_validator" }
   ]
  },
  { "title": "Explorer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Current Era",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(current_era{job=\"casper\"})"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 2, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "peers{job=\"casper\"}"
    }
   ]
  },
  {
   "title": "Current Block Height",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(chain_height{job=\"casper\"})"
    }
   ]
  },
  {
   "title": "Finalization Time(s)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "finalization_time{job=\"casper\"}/1000 > 0"
    }
   ]
  },
  {
   "title": "Block Time(s)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max_over_time(timestamp(changes(amount_of_blocks{job=\"casper\"}[30s]) > 0)[1h:15s])"
    }
   ]
  },
  {
   "title": "pending_deploy",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "max(pending_deploy)" }
   ]
  },
  {
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "casper_exporter_general_info_info",
     "legendFormat": "api version"
    }
   ]
  },
  {
   "title": "Block Finalization Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms", "label": "finalization time" }
   ],
   "targets": [
    { "expr": "finalization_time > 0", "legendFormat": "Finalization Time" }
   ]
  },
  {
   "title": "Block Time Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum(avg(rate(chain_height[1h])))",
     "legendFormat": "rate 1h"
    },
    {
     "expr": "sum(avg(rate(chain_height[6h])))",
     "legendFormat": "rate 6h"
    },
    {
     "expr": "sum(avg(rate(chain_height[24h])))",
     "legendFormat": "rate 24h"
    }
   ]
  },
  {
   "title": "Pending Deploys",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pending_deploy", "legendFormat": "Pending deploys" }
   ]
  },
  {
   "title": "Consensus Finalized Block Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 9, "y": 14 },
   "yaxes": [
    { "format": "none", "label": "Number of Blocks" }
   ],
   "targets": [
    {
     "expr": "amount_of_blocks{job=\"casper\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Consensus Finalized Block Interval",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 14 },
   "yaxes": [
    { "format": "dateTimeFromNow", "label": "Number of Blocks" }
   ],
   "targets": [
    {
     "expr": "timestamp(changes(amount_of_blocks{job=\"casper\"}[30s]) > 0) * 1000",
     "legendFormat": "Consensus Finalized Block Interval"
    }
   ]
  },
  {
   "title": "Validation Flow",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "casper_exporter_last_added_block_info_info"
    }
   ]
  },
  {
   "title": "Ongoing Era",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(current_era{job=\"casper\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Network Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Run execute p95",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, contract_runtime_run_execute_bucket)",
     "legendFormat": "p95  {{instance}}"
    }
   ]
  },
  {
   "title": "Average Mem (REST vs RPC)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "avg(mem_rest_server)", "legendFormat": "Average Mem (REST)" },
    { "expr": "avg(mem_rpc_server)", "legendFormat": "Average Mem (RPC)" }
   ]
  },
  {
   "title": "amount_of_blocks",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "amount_of_blocks" }
   ]
  },
  {
   "title": "Mem Total",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "mem_total", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Mem Consensus",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "mem_consensus" }
   ]
  },
  {
   "title": "allocated_ram_bytes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "allocated_ram_bytes" }
   ]
  },
  {
   "title": "Run execute cumulative count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "none", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "contract_runtime_run_execute_count",
     "legendFormat": "count {{instance}}"
    }
   ]
  },
  {
   "title": "block_completion_duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "block_completion_duration", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Mem Block Executor",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "mem_block_executor", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Run execute cumulative count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "none", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "contract_runtime_run_execute_count",
     "legendFormat": "count {{instance}}"
    }
   ]
  },
  {
   "title": "Mem Linear Chain",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "mem_linear_chain", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Scheduler Queue Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    { "expr": "scheduler_queue_total_count" }
   ]
  },
  {
   "title": "Run commit",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, contract_runtime_apply_commit_bucket)",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Mem Block Proposer",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "mem_block_proposer", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Ran out of Peers - Address vs Deploy",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deploy_gossiper_times_ran_out_of_peers",
     "legendFormat": "deploy"
    },
    {
     "expr": "address_gossiper_times_ran_out_of_peers",
     "legendFormat": "address"
    }
   ]
  },
  {
   "title": "Scheduler Queue Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    { "expr": "scheduler_queue_total_count", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Average Mem (REST vs RPC)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Bytes" }
   ],
   "targets": [
    { "expr": "avg(mem_rest_server)", "legendFormat": "Average Mem (REST)" },
    { "expr": "avg(mem_rpc_server)", "legendFormat": "Average Mem (RPC)" }
   ]
  },
  {
   "title": "Finalization Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Seconds" }
   ],
   "targets": [
    { "expr": "finalization_time / 1000", "legendFormat": " " }
   ]
  },
  { "title": "Deploys", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Pending Deploys",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "none", "label": "Deploy Count" }
   ],
   "targets": [
    { "expr": "pending_deploy", "legendFormat": " " }
   ]
  },
  {
   "title": "Deploy Gossiper Table -  finished.",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deploy_gossiper_table_items_finished",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Deploy Gossiper Table - Paused",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deploy_gossiper_table_items_paused",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Deploy Gossiper Table -  current.",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deploy_gossiper_table_items_current",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Mem Deploy Gossiper",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "mem_deploy_gossiper", "legendFormat": " " }
   ]
  },
  {
   "title": "Alert Utility ( for setting alerts )",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 }
  },
  {
   "title": "Validator State Alert",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short", "label": "Validator Status" }
   ],
   "targets": [
    { "expr": "casper_exporter_is_validator", "legendFormat": "Validator Status" }
   ]
  },
  {
   "title": "Lack Of Peers Alert",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 68 },
   "yaxes": [
    { "format": "short", "label": "Connected Peers" }
   ],
   "targets": [
    { "expr": "casper_exporter_peer_count", "legendFormat": "Amount of peers:" }
   ]
  },
  {
   "title": "Block Time(s) Alert",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 68 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - max_over_time(timestamp(changes(amount_of_blocks{job=\"casper\"}[30s]) > 0)[1h:15s])",
     "legendFormat": "Block Time:"
    }
   ]
  },
  {
   "title": "Delta Chain Flow Halt Alert",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(amount_of_blocks{job=\"casper\"}[5m])",
     "legendFormat": "Delta Chain Flow:"
    }
   ]
  }
 ]
}